version: "3.8"

services:
  app:
    build:
      context: ./app
    volumes:
      - ./app:/home/pyuser/app
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
    command: uvicorn app.main:app --host "0.0.0.0" --port "8000" --reload

  # db:
  #   image: mariadb
