version: "3.8"

services:
  app:
    build:
      context: ./app
    volumes:
      - ./app:/home/pyuser/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: uvicorn app.main:app --host "0.0.0.0" --port "8000" --reload

  db:
    image: postgres:16-alpine
    volumes:
      - "db_data:/var/lib/postgresql/data/"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  db_data:
