version: "3.8"

services:
  app:
    build:
      context: ./app
    volumes:
      - ./app:/app
      - /app/node_modules # exclude node_modules
    ports:
      - "5173:5173"
    command: npm run dev
